// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/cli/app.go

// Package cli is a generated GoMock package.
package cli

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/hw4-fractal-flame/internal/domain"
)

// MockFlameService is a mock of FlameService interface.
type MockFlameService struct {
	ctrl     *gomock.Controller
	recorder *MockFlameServiceMockRecorder
}

// MockFlameServiceMockRecorder is the mock recorder for MockFlameService.
type MockFlameServiceMockRecorder struct {
	mock *MockFlameService
}

// NewMockFlameService creates a new mock instance.
func NewMockFlameService(ctrl *gomock.Controller) *MockFlameService {
	mock := &MockFlameService{ctrl: ctrl}
	mock.recorder = &MockFlameServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlameService) EXPECT() *MockFlameServiceMockRecorder {
	return m.recorder
}

// RenderFlame mocks base method.
func (m *MockFlameService) RenderFlame(args *domain.Args) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderFlame", args)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenderFlame indicates an expected call of RenderFlame.
func (mr *MockFlameServiceMockRecorder) RenderFlame(args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderFlame", reflect.TypeOf((*MockFlameService)(nil).RenderFlame), args)
}
