// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/renderers/renderer_chooser.go

// Package renderer is a generated GoMock package.
package renderer

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	random "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/hw4-fractal-flame/pkg/random"
)

// MockRandomGenerator is a mock of RandomGenerator interface.
type MockRandomGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockRandomGeneratorMockRecorder
}

// MockRandomGeneratorMockRecorder is the mock recorder for MockRandomGenerator.
type MockRandomGeneratorMockRecorder struct {
	mock *MockRandomGenerator
}

// NewMockRandomGenerator creates a new mock instance.
func NewMockRandomGenerator(ctrl *gomock.Controller) *MockRandomGenerator {
	mock := &MockRandomGenerator{ctrl: ctrl}
	mock.recorder = &MockRandomGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRandomGenerator) EXPECT() *MockRandomGeneratorMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockRandomGenerator) New(seed int64) random.Random {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", seed)
	ret0, _ := ret[0].(random.Random)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockRandomGeneratorMockRecorder) New(seed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockRandomGenerator)(nil).New), seed)
}
